name: Daily Contribution Streak

on:
  schedule:
    - cron: '0 3,9,15,21 * * *'
  workflow_dispatch:

jobs:
  create-commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # Ensure default branch
          fetch-depth: 1
      
      - name: Setup Git
        run: |
          git config --local user.email "gamingcristy19@gmail.com"
          git config --local user.name "Burhanali2211"
      
      - name: Generate commits
        run: |
          COMMIT_COUNT=3  # Limited to avoid spam detection
          echo "Will create $COMMIT_COUNT commits"
          
          for i in $(seq 1 $COMMIT_COUNT)
          do
            TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
            # Append to streak.txt for meaningful change
            echo "Commit #$i on $TIMESTAMP" >> streak.txt
            
            git add streak.txt
            git commit -m "feat: daily contribution #$i/$COMMIT_COUNT [$TIMESTAMP]"
            
            sleep 60  # Delay to space commits
          done
      
      - name: Push changes
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
